# Generated by Django 4.2.3 on 2023-08-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assigner", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("D", "Draft"), ("O", "Ongoing"), ("C", "Completed")],
                default="D",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("D", "Draft"), ("O", "Ongoing"), ("C", "Completed")],
                default="D",
                max_length=1,
            ),
        ),
    ]
