# Generated by Django 4.2.3 on 2023-08-01 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("assigner", "0003_project_status_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
