# Generated by Django 4.2.3 on 2023-08-01 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assigner", "0007_submittedtask_remarks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submittedtask",
            name="submitter",
        ),
        migrations.AddField(
            model_name="submittedtask",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submit_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submittedtask",
            name="modifier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submit_modifier",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
